spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sukee_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:liquibase/master.yml
